steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/jubilant-doodle/back:latest
      - --dockerfile=back/Dockerfile
      - --cache=true
      - --cache-ttl=24h
